# Dockerfile for the frontend (React)
FROM node:22.6.0-alpine3.19

WORKDIR /app

# COPY package.json ./
# COPY package-lock.json ./
COPY Frontend/. .

#RUN npm install
#RUN npm run build
# RUN npm install -g serve
# CMD ["serve", "-s", "dist"]

ENTRYPOINT ["sh", "/app/entrypoint.sh"]